/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSpecializedProgramsRouteImport } from './routes/services.specialized-programs'
import { Route as ServicesRehabilitationRouteImport } from './routes/services.rehabilitation'
import { Route as ServicesPaediatricAudiologyRouteImport } from './routes/services.paediatric-audiology'
import { Route as ServicesHearingDevicesRouteImport } from './routes/services.hearing-devices'
import { Route as ServicesClinicalAudiologyRouteImport } from './routes/services.clinical-audiology'
import { Route as ResourcesHearingAidsGuideRouteImport } from './routes/resources.hearing-aids-guide'
import { Route as ResourcesFirstAppointmentRouteImport } from './routes/resources.first-appointment'
import { Route as ResourcesFaqsRouteImport } from './routes/resources.faqs'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSpecializedProgramsRoute =
  ServicesSpecializedProgramsRouteImport.update({
    id: '/specialized-programs',
    path: '/specialized-programs',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesRehabilitationRoute = ServicesRehabilitationRouteImport.update({
  id: '/rehabilitation',
  path: '/rehabilitation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPaediatricAudiologyRoute =
  ServicesPaediatricAudiologyRouteImport.update({
    id: '/paediatric-audiology',
    path: '/paediatric-audiology',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHearingDevicesRoute = ServicesHearingDevicesRouteImport.update({
  id: '/hearing-devices',
  path: '/hearing-devices',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesClinicalAudiologyRoute =
  ServicesClinicalAudiologyRouteImport.update({
    id: '/clinical-audiology',
    path: '/clinical-audiology',
    getParentRoute: () => ServicesRoute,
  } as any)
const ResourcesHearingAidsGuideRoute =
  ResourcesHearingAidsGuideRouteImport.update({
    id: '/hearing-aids-guide',
    path: '/hearing-aids-guide',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesFirstAppointmentRoute =
  ResourcesFirstAppointmentRouteImport.update({
    id: '/first-appointment',
    path: '/first-appointment',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesFaqsRoute = ResourcesFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/resources/faqs': typeof ResourcesFaqsRoute
  '/resources/first-appointment': typeof ResourcesFirstAppointmentRoute
  '/resources/hearing-aids-guide': typeof ResourcesHearingAidsGuideRoute
  '/services/clinical-audiology': typeof ServicesClinicalAudiologyRoute
  '/services/hearing-devices': typeof ServicesHearingDevicesRoute
  '/services/paediatric-audiology': typeof ServicesPaediatricAudiologyRoute
  '/services/rehabilitation': typeof ServicesRehabilitationRoute
  '/services/specialized-programs': typeof ServicesSpecializedProgramsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/resources/faqs': typeof ResourcesFaqsRoute
  '/resources/first-appointment': typeof ResourcesFirstAppointmentRoute
  '/resources/hearing-aids-guide': typeof ResourcesHearingAidsGuideRoute
  '/services/clinical-audiology': typeof ServicesClinicalAudiologyRoute
  '/services/hearing-devices': typeof ServicesHearingDevicesRoute
  '/services/paediatric-audiology': typeof ServicesPaediatricAudiologyRoute
  '/services/rehabilitation': typeof ServicesRehabilitationRoute
  '/services/specialized-programs': typeof ServicesSpecializedProgramsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/resources/faqs': typeof ResourcesFaqsRoute
  '/resources/first-appointment': typeof ResourcesFirstAppointmentRoute
  '/resources/hearing-aids-guide': typeof ResourcesHearingAidsGuideRoute
  '/services/clinical-audiology': typeof ServicesClinicalAudiologyRoute
  '/services/hearing-devices': typeof ServicesHearingDevicesRoute
  '/services/paediatric-audiology': typeof ServicesPaediatricAudiologyRoute
  '/services/rehabilitation': typeof ServicesRehabilitationRoute
  '/services/specialized-programs': typeof ServicesSpecializedProgramsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/contact'
    | '/news'
    | '/resources'
    | '/services'
    | '/resources/faqs'
    | '/resources/first-appointment'
    | '/resources/hearing-aids-guide'
    | '/services/clinical-audiology'
    | '/services/hearing-devices'
    | '/services/paediatric-audiology'
    | '/services/rehabilitation'
    | '/services/specialized-programs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/contact'
    | '/news'
    | '/resources'
    | '/services'
    | '/resources/faqs'
    | '/resources/first-appointment'
    | '/resources/hearing-aids-guide'
    | '/services/clinical-audiology'
    | '/services/hearing-devices'
    | '/services/paediatric-audiology'
    | '/services/rehabilitation'
    | '/services/specialized-programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointments'
    | '/contact'
    | '/news'
    | '/resources'
    | '/services'
    | '/resources/faqs'
    | '/resources/first-appointment'
    | '/resources/hearing-aids-guide'
    | '/services/clinical-audiology'
    | '/services/hearing-devices'
    | '/services/paediatric-audiology'
    | '/services/rehabilitation'
    | '/services/specialized-programs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/specialized-programs': {
      id: '/services/specialized-programs'
      path: '/specialized-programs'
      fullPath: '/services/specialized-programs'
      preLoaderRoute: typeof ServicesSpecializedProgramsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/rehabilitation': {
      id: '/services/rehabilitation'
      path: '/rehabilitation'
      fullPath: '/services/rehabilitation'
      preLoaderRoute: typeof ServicesRehabilitationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/paediatric-audiology': {
      id: '/services/paediatric-audiology'
      path: '/paediatric-audiology'
      fullPath: '/services/paediatric-audiology'
      preLoaderRoute: typeof ServicesPaediatricAudiologyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hearing-devices': {
      id: '/services/hearing-devices'
      path: '/hearing-devices'
      fullPath: '/services/hearing-devices'
      preLoaderRoute: typeof ServicesHearingDevicesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/clinical-audiology': {
      id: '/services/clinical-audiology'
      path: '/clinical-audiology'
      fullPath: '/services/clinical-audiology'
      preLoaderRoute: typeof ServicesClinicalAudiologyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/resources/hearing-aids-guide': {
      id: '/resources/hearing-aids-guide'
      path: '/hearing-aids-guide'
      fullPath: '/resources/hearing-aids-guide'
      preLoaderRoute: typeof ResourcesHearingAidsGuideRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/first-appointment': {
      id: '/resources/first-appointment'
      path: '/first-appointment'
      fullPath: '/resources/first-appointment'
      preLoaderRoute: typeof ResourcesFirstAppointmentRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/faqs': {
      id: '/resources/faqs'
      path: '/faqs'
      fullPath: '/resources/faqs'
      preLoaderRoute: typeof ResourcesFaqsRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesFaqsRoute: typeof ResourcesFaqsRoute
  ResourcesFirstAppointmentRoute: typeof ResourcesFirstAppointmentRoute
  ResourcesHearingAidsGuideRoute: typeof ResourcesHearingAidsGuideRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesFaqsRoute: ResourcesFaqsRoute,
  ResourcesFirstAppointmentRoute: ResourcesFirstAppointmentRoute,
  ResourcesHearingAidsGuideRoute: ResourcesHearingAidsGuideRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesClinicalAudiologyRoute: typeof ServicesClinicalAudiologyRoute
  ServicesHearingDevicesRoute: typeof ServicesHearingDevicesRoute
  ServicesPaediatricAudiologyRoute: typeof ServicesPaediatricAudiologyRoute
  ServicesRehabilitationRoute: typeof ServicesRehabilitationRoute
  ServicesSpecializedProgramsRoute: typeof ServicesSpecializedProgramsRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesClinicalAudiologyRoute: ServicesClinicalAudiologyRoute,
  ServicesHearingDevicesRoute: ServicesHearingDevicesRoute,
  ServicesPaediatricAudiologyRoute: ServicesPaediatricAudiologyRoute,
  ServicesRehabilitationRoute: ServicesRehabilitationRoute,
  ServicesSpecializedProgramsRoute: ServicesSpecializedProgramsRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
